### ISSUE TITLE
A problem for the function correlationPlot()

### ISSUE THREAD

**Issue by 12038019** [eead-csic-eesa/fingerPro#2]
Dear guy, why did I always meet the problem using the example data-catchment?
If I use my own data, the problem will miss. 
Is there something wrong with the data?

> data <- catchment
> correlationPlot(data, columns = 1:5, mixtures = F)
 plot: [2,3] [==============>-------------------------------] 32% est: 3s Error in cor.test.default(x, y, method = method, use = use) : 
  not enough finite observations
此外: Warning messages:
1: Groups with fewer than two data points have been dropped. 
2: Removed 1 row(s) containing missing values (geom_path). 
3: Groups with fewer than two data points have been dropped. 
4: In max(ids, na.rm = TRUE) : max里所有的参数都不存在；回覆-Inf
5: In cor(x, y) : 标准差为零

**Comment by ivanlizaga** [comment]
Dear user,
The issue was solved in FingerPro version 1.2 and also in 1.3 with some further improvements in this specific function together with the inclusion of all the CI, CR and CTS methods.
The last version will be soon available in CRAN. Still, to keep your package updated, I recommend installing it from the GitHub repository following the provided instruction in the installation section.
https://github.com/eead-csic-eesa/fingerPro#installation
A lot is coming in the coming months, so keep it updated. Among these new things is the method to combine tracers of different nature, such as isotopic ratios and geochemistry.
https://www.sciencedirect.com/science/article/pii/S0048969722019271?via%3Dihub
Cheers,
Ivan

**Comment by 12038019** [comment]
> Dear Ivan， 
 I hope this message finds you well, and thanks for your kind reply!
 Recently, I have been trying to learn how to use the R packages FingerPro to analyze my own data.
 It definitely provides a useful and effective tool for sediment fingerprinting and tracing. Excited and happy.
 I hope the coming new version and informative functions.
 Thanks for what you have done.

Best wishes,
